### ISSUE TITLE
Hiding dropdown not working in mobile & ipad devises

### ISSUE THREAD

**Issue by PirunSeng** [mkhairi/materialize-sass#102]
Hi,
I'm using a dropdown menu which works fine on my pc.
However, there is one thing not working in mobile & ipad devises.

On my mobile & ipad devises, I can click the dropdown menu to show its dropdown lists, but I when I want to hide it by clicking somewhere outside, the dropdown lists do not disappear. This works fine on pc, but why not on mobile & ipad devises.

**Comment by mkhairi** [comment]
try check with latest release of materializecss. 
closing old issue.
