### ISSUE TITLE
materialize sass variable cheat sheet

### ISSUE THREAD

**Issue by marmikdesai** [mkhairi/materialize-sass#103]
Hi,

Is there materialize sass variable cheat sheet available? I found for [bootstrap](https://www.cheatography.com/masonjo/cheat-sheets/bootstrap/).

**Comment by requnix** [comment]
I'm guessing you don't need this anymore, but you can look at the [variables partial](https://github.com/mkhairi/materialize-sass/blob/master/app/assets/stylesheets/materialize/components/_variables.scss). All the SASS variables are defined there. Perhaps someone else will find this useful.
