### ISSUE TITLE
Update assets commit

### ISSUE THREAD

**Issue by danReynolds** [mkhairi/materialize-sass#117]
The commit c48453a99f831b665815575e392de4db49f89558 had some breaking changes for modal functionality. I notice that http://materializecss.com/modals.html still references the lean modal version and that https://github.com/mkhairi/materialize-sass/blob/master/app/assets/javascripts/materialize.js is still using the old version. I'm excited for modal improvements but was wondering if you could tell me more about why this change was made and which one should be consistent across the docs and codebase.

Thanks

**Comment by mkhairi** [comment]
@danReynolds, sorry about that. this repo was regularly update from orignal repo https://github.com/Dogfalo/materialize. You can check a latest documentation from original repo at master branch. You should refer documentation version http://materializecss.com with same version of published gem on http://rubygems.org
