### ISSUE TITLE
Rails dynamic dropdown not updating

### ISSUE THREAD

**Issue by reckerswartz** [mkhairi/materialize-sass#118]
I using materialize-sass gem in my rails application. In my application I need to alter the second drop-down menu on based of first drop-down selected options. 

My JS
 var branch = $('#user_branch_id').html();
  $('#user_course_id').change(function(){
    var selectedCourseCategory = $('#user_course_id :selected').text();
    var optgroup = "optgroup[label="+ selectedCourseCategory + "]";
    var branchOptions = $(branch).filter(optgroup).html();
    console.log(branchOptions);
    if (branchOptions) {
      $('#user_branch_id').html(branchOptions);

```
  $('#user_branch_id').trigger('contentChanged');

  $('select').on('contentChanged', function() {
          // re-initialize (update)
        $(this).material_select();
    });


}
```

  });
}

HTML------------------------------------------------------------------------------------

<div class="row">
       
        <div class="input-field col s12">
          <%= f.collection_select :course_id, Course.order(:name), :id, :name, include_blank: 'Select an Course...' %>
        </div>
         

  </div>
  <div class="row">

```
    <div class="input-field col s12">
      <%= f.grouped_collection_select :branch_id, Course.order(:name), :branches, :name, :id, :name, include_blank: 'Select an Branch...' %>
    </div>
```
## Its changing the elements when inspected using developer tools but it seems that materialize-sass creating another dropdown to display

<div class="select-wrapper">
<span class="caret">▼</span>
<input class="select-dropdown" readonly="true" data-activates="select-options-149665e9-f9ba-b1f6-76a4-d3855397a6bf" value="Select an Branch..." type="text">
<ul id="select-options-149665e9-f9ba-b1f6-76a4-d3855397a6bf" class="dropdown-content select-dropdown "><li class=""><span>Select an Branch...</span></li>
<li class="optgroup"><span>postgraduate</span></li><li class="optgroup-option "><span>MCA</span></li><li class="optgroup"><span>undergraduate</span></li><li class="optgroup-option "><span>BCA</span></li><li class="optgroup-option "><span>BTECH</span></li></ul> 
--------------------------------------------------------below it which is altered using java script--------
<select name="user[branch_id]" id="user_branch_id" class="initialized"><option value="2">MCA</option></select></div>

---

How can i create dynamic drop-down and also show the chances in real time.

For reference you can look into the file @ https://ide.c9.io/reckerswartz/mgr

**Comment by mkhairi** [comment]
try check with latest release of materializecss.
closing old issue.
