### ISSUE TITLE
Update to Materialize 0.97.8?

### ISSUE THREAD

**Issue by bkraeling** [mkhairi/materialize-sass#123]

**Comment by ReckerSwartz** [comment]
still waiting

**Comment by ReckerSwartz** [comment]
Hey when you going to update it ?

**Comment by frizbee** [comment]
`bundle update`Because for me it is already 0.97.8

Gemfile.lock 
```
.....
materialize-sass
.......
materialize-sass (0.97.8)
     sass (~> 3.3)
......
```
Gemfile
```
gem 'materialize-sass'
```

And it is faild for me while capistrano deploy.
```
rake aborted!
Sass::SyntaxError: File to import not found or unreadable: materialize/components/form.
```

**Comment by mkhairi** [comment]
@frizbee 
new path ``` @import "materialize/components/forms/forms"; ```

**Comment by mkhairi** [comment]
@ReckerSwartz, @bkraeling gem v0.97.8 has been published.

**Comment by frizbee** [comment]
Awesome @mkhairi
