### ISSUE TITLE
Media queries and break points

### ISSUE THREAD

**Issue by swilson223** [mkhairi/materialize-sass#126]
I am trying to find your media queries and breakpoints and have been un able to do so, could you kindly post the ink or place them here?

**Comment by rubendinho** [comment]
These should be in [_variables.scss](https://github.com/mkhairi/materialize-sass/blob/master/app/assets/stylesheets/materialize/components/_variables.scss)

**Comment by swilson223** [comment]
thanks so much i completely missed them in there the first go around! Many thanks.
