### ISSUE TITLE
Canot change sass variables

### ISSUE THREAD

**Issue by sdefrancesco** [mkhairi/materialize-sass#128]
I get an error after putting this in my application.scss file:

'@import "materialize/components/color";
$primary-color: color("blue", "lighten-2") !default;
$secondary-color: color("yellow") !default;
@import 'materialize''

**the error looks like this :** 

Function color is missing argument $type.

**Comment by rubendinho** [comment]
Try:
> $secondary-color: color("yellow", "base") !default;
> 


Ruben Izmailyan
Budgit
ruben@budgit.com

**Comment by sdefrancesco** [comment]
Thank you  rubendinho! You saved my life!!!!
