### ISSUE TITLE
Publish 0.95.2 version on rubygems

### ISSUE THREAD

**Issue by xamenrax** [mkhairi/materialize-sass#13]
@mkhairi

**Comment by mkhairi** [comment]
:thumbsup: :thumbsup:

**Comment by mkhairi** [comment]
@xamenrax did you have rubygems account? if you don't mind, i would like to adding you as gem onwer

**Comment by xamenrax** [comment]
@mkhairi  yep!
https://rubygems.org/profiles/xamenrax
email: xamenrax@gmail.com

**Comment by mkhairi** [comment]
:ok_hand:
