### ISSUE TITLE
Turbolinks crashes when going back and forth in the browser without reloading the page manually!

### ISSUE THREAD

**Issue by AlexVentura** [mkhairi/materialize-sass#130]
Hi there! As the docs says we need to call an *initializer* for some JS components [like this](http://materializecss.com/forms.html#select).

My doubt is, **where to put the initializers?** because I put it at the end of my form view into a `script` html tag and it works fine but when I push the **browser's back button** and then the **forward button** without refreshing the page, it seems like to render nested JS components into itself. I mean, using the inspector, the html code looks like callbacks in JS.

![screen shot 2016-12-15 at 22 30 00](https://cloud.githubusercontent.com/assets/13169164/21251789/6101cc32-c316-11e6-9386-81cfab9e7adc.png)

And it increases as many times you go back and forward until you refresh the page.

<img width="1000" alt="screen shot 2016-12-15 at 22 27 19" src="https://cloud.githubusercontent.com/assets/13169164/21251715/b9263156-c315-11e6-8bfb-f22b9456b198.png">

So where to put this JS initializer code in order to be executed only once or maybe how to force the browser to refresh the page on every back and forward action in order to show only one of the components?

This is my code:
```
<script>
    $(document).ready(function () {
        $('select').material_select();
    });
</script>

**Comment by oscartzgz** [comment]
If you uses turbolinks you can put the code in assets/application.js like this:
`$(document).on('turbolinks:load', function() {
      $('select').material_select();
});`

**Comment by AlexVentura** [comment]
Thanks @oscartzgz I have done what you said but I still getting the same behavior when I go back and forward with out reloading the page. It seems to be creating components on the fly. Even though I'm using turbo links with the `turbolinks:load` event handler.

**Comment by mkhairi** [comment]
try

```
<head>
  ...
  <meta name="turbolinks-cache-control" content="no-preview">
</head>
```
see https://github.com/turbolinks/turbolinks#opting-out-of-caching

**Comment by ttrmw** [comment]
Same issue here. I initialize the select as you've indicated, on `turbolinks:load`, and have tried adding the meta tag but to no effect. Mi

**Comment by fwoelm** [comment]
If you use Turbolinks, you want to destroy the select before the page is cached by calling `$('select').material_select('destroy');` (see _Updating/Destroying Select_ in [Forms](http://materializecss.com/forms.html)).

This is written in Coffeescript [so you'll need to convert it](http://coffeescript.org/#try:%23%20app%2Fassets%2Fjavascripts%2Fhelpers%2Fmaterialize.coffee%0A%23%20Make%20sure%20this%20file%20is%20loaded%20on%20every%20page%20load%20(it%20will%20be%20if%20you%20have%20the%20line%20%2F%2F%3D%20require_tree%20.%20in%20app%2Fassets%2Fjavascripts%2Fapplication.js)%0A%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%0A%23%23%20Helper%20file%20to%20make%20Materialize%20work%20with%20Turbolinks%20%23%23%23%23%23%23%0A%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%0A%0A%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%0A%23%23%20ON%20LOAD%20%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%0A%23%23%20Actions%20to%20be%20executed%20on%20page%20load%20(first%20or%20history)%20%23%23%23%23%0A%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%0A%24(document).on%20%27turbolinks%3Aload%27%2C%20-%3E%0A%0A%20%23%20bunch%20of%20stuff%20here%20(fixing%20tooltips%2C%20datepicker%2C%20etc...)%0A%0A%20%23%20initialize%20selects%0A%20%24(%27select%27).material_select()%0A%0A%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%0A%23%23%20BEFORE%20CACHE%20%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%0A%23%23%20Actions%20to%20be%20executed%20before%20Turbolinks%20caches%20the%20page%20%23%23%0A%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%20%0A%24(document).on%20%27turbolinks%3Abefore-cache%27%2C%20-%3E%0A%0A%20%23%20bunch%20of%20stuff%20here%20(fixing%20tooltips%2C%20datepicker%2C%20etc...)%0A%0A%20%23%20destroy%20selects%0A%20%24(%27select%27).material_select(%27destroy%27)%3B), but here is what I do:

    # app/assets/javascripts/helpers/materialize.coffee
    # Make sure this file is loaded on every page load (it will be if you have the line //= require_tree . in app/assets/javascripts/application.js)
    ##############################################################
    ## Helper file to make Materialize work with Turbolinks ######
    ##############################################################

    ##############################################################
    ## ON LOAD ###################################################
    ## Actions to be executed on page load (first or history) ####
    ##############################################################
    $(document).on 'turbolinks:load', ->

      # bunch of stuff here (fixing tooltips, datepicker, etc...)

      # initialize selects
      $('select').material_select()

    ##############################################################
    ## BEFORE CACHE ##############################################
    ## Actions to be executed before Turbolinks caches the page ##
    ##############################################################   
    $(document).on 'turbolinks:before-cache', ->

      # bunch of stuff here (fixing tooltips, datepicker, etc...)

      # destroy selects
      $('select').material_select('destroy');

**Comment by AlexVentura** [comment]
Yes! @fwoelm you're right. It has to see with the JS elements cached when loading pages. But I do something a little bit different and that's how I'm solving the issue right now. With `Toast` elements I call another method which is actually not included in the [Materialize documentation](http://materializecss.com/dialogs.html#toast) but in the jQuery docs `.remove()`.

So, this is what I'm doing:

```
$(document).on("turbolinks:before-cache", function () {
	// Destroy cached JS elements on turbolinks 'before-cache' to recreate new ones on 'load' event
	$('select').material_select('destroy');
	$('.toast').remove();
});
```
I tell jQuery to select all the HTML elements with the `toast` class and then just remove them.

And it works like a charm! 😃 
So, it is solved by the moment!
