### ISSUE TITLE
icon it dont't work

### ISSUE THREAD

**Issue by marcosvicente** [mkhairi/materialize-sass#131]
I have a project in rails 4.2.5.1, and don't work a icon anybody can help me?

**Comment by andrewdruzhinin** [comment]
@marcosvicente show code plz

**Comment by ttrmw** [comment]
Hey, I'm having a similar issue. In slim:

```
i.material-icons
  | playlist_add
```
No icon shows, just the text playlist_add.

**Comment by andrewdruzhinin** [comment]
@ttrmw do you added `stylesheet_link_tag 'http://fonts.googleapis.com/icon?family=Material+Icons'` in layout?

**Comment by marcosvicente** [comment]
I can solve the problem thank guys.

**Comment by ttrmw** [comment]
Hi @andrewdruzhinin nope, is there a way to get this working without hitting an external API?

**Comment by ttrmw** [comment]
eh, disregard that - seen the material_icons gem recommended on other issues, thanks anyway :)

**Comment by marcosvicente** [comment]
II use the material_icons for solve the problem thanks for help me
