### ISSUE TITLE
.tabs() Uncaught TypeError: Cannot read property 'left' of undefined

### ISSUE THREAD

**Issue by thalesmiguel** [mkhairi/materialize-sass#138]
Hello.
I've just updated this awesome gem on my project and I'm getting an error when initializing my tabs.
When using `$(ul.tabs).tabs();` I get a `Uncaught TypeError: Cannot read property 'left' of undefined`.

Anyone else getting this message?

Thanks in advance.

**Comment by thalesmiguel** [comment]
Ok... Found it out.
Just wrapped all my **js** file with `$(() => {});`

**Comment by aeroreyna** [comment]
Happen to me too. Is there a solution?

**Comment by mkhairi** [comment]
try update update gem with latest release

**Comment by aeroreyna** [comment]
In my case, I was using <div> instead of <li> for each item, inside the <ul>. Using <li> solves the problem for me.

**Comment by qantumthemes** [comment]
the js shoudln't throw errors because of the html.
To fix the tabs.js you have to add a control in tabs.js line 42 and 49
 _if(undefined === el.position())  {return;}_

```
 var calcRightPos = function(el) {
        if(undefined === el.position())  {return;}
        return Math.ceil($tabs_width - el.position().left - el.outerWidth() - $this.scrollLeft());
      };

 var calcLeftPos = function(el) {
        if(undefined === el.position())  {return;}
        return Math.floor(el.position().left + $this.scrollLeft());
      };
```

**Comment by woohyodong** [comment]
Change ul -> ol
