### ISSUE TITLE
couldn't find file 'materialize-sprockets'

### ISSUE THREAD

**Issue by sbrocos** [mkhairi/materialize-sass#14]
when write in application.js -> //= require materialize-sprockets
then show the next message:

**Sprockets::FileNotFound in Public#index**

couldn't find file 'materialize-sprockets'

**Comment by denqxotl** [comment]
+1

**Comment by mkhairi** [comment]
new gem version 0.95.2 has been published. Seem like gem version 0.95.1  has typo for file "materialize-sprockets" => "materialize-sprokets"

**Comment by xamenrax** [comment]
Yeah, I think it's better to get gem from github repo (master branch) until 1.0 version is released.
Can we close the issue though?
