### ISSUE TITLE
turbolinks 5 users still need the jquery turbolinks

### ISSUE THREAD

**Issue by Feuda** [mkhairi/materialize-sass#141]
![screenshot from 2017-03-31 18 22 10](https://cloud.githubusercontent.com/assets/436635/24546705/17cabd9a-163f-11e7-824d-7d4a12a1b2d8.png)

**Comment by Feuda** [comment]
![screenshot from 2017-03-31 18 22 10](https://cloud.githubusercontent.com/assets/436635/24546686/0177e018-163f-11e7-91d5-1fca255e3e62.png)

**Comment by QuintinAdam** [comment]
I could be wrong. But last time I checked jquery turbolinks does not support turbolinks 5. 

For a workaround, I simply wrap any materialize initialize code into a turbolinks:load event listener

```
document.addEventListener "turbolinks:load", (event) ->
  $(".button-collapse").sideNav()
  $('select').material_select()
```
