### ISSUE TITLE
Buttons click-listener registered multiple times

### ISSUE THREAD

**Issue by axelerator** [mkhairi/materialize-sass#144]
I'm not sure if you are aware of the fact that ` 'turbolinks:load'` is triggered on **every page change** (link click).

https://github.com/mkhairi/materialize-sass/blob/master/app/assets/javascripts/materialize/buttons.js#L2

This means all these `on-click`-Listeners are registered multiple times.
This leads to funny behavior like then 'click-only-fab' only working on every other page. 

* initial page load -> 1 event listener -> 'click' -> toggle once -> it's open!
* after first page change: -> 2 event listeners -> 'click' -> toggle twice -> it's closed
* after second page change: -> 3 event listeners -> 'click' -> toggle three times -> it's open!
* and so on

And I fear it's not the only widget affected by that :-/

**Comment by mkhairi** [comment]
i can't reproduce this.
Everything seems to be working fine.
checkout  http://materialize-rails.herokuapp.com/components
