### ISSUE TITLE
onShow not triggered in version 0.98.2

### ISSUE THREAD

**Issue by nocivus** [mkhairi/materialize-sass#147]
onShow is not being called in the latest version (0.98.2).

Looking at the code, the off and on trigger definitions where changed from "click" to "click.tabs". However, when the tab changes, the "click" event is triggered. Can this be the reason? Because if i change the off and on definitions back to "click" it all works again.

Cheers

**Comment by mkhairi** [comment]
i need more info/sample code to reproduce this issue

**Comment by mkhairi** [comment]
you may retry by using latest released version.
