### ISSUE TITLE
Navbar shows items menù on top, not in the middle of the bar (as expected)

### ISSUE THREAD

**Issue by giacomo-giovenzana** [mkhairi/materialize-sass#154]
I am using rails 5.1.1 and I have done following step:

1. generated new project (ex. rails new blog)
2. filled "gem 'materialize-sass'" into Gemfile && run bundle install
3. added "@import "materialize";" into applications.scss
4. added the javascript for  turbolink
5. simply copied & paste the "right aligned link" from Navbar page (I have taken exactly the example and I ha passed it inside my layout/application). I have used a ruby partial but I think it doesn't matter

When I start the server and I load the welcome page,  I see the Navbar on the top of my page, but the listed menù items are aligned on top of the bar, not on the middle as the shown in the example.
I expect to have the items menù vertically centered inside the Navbar.
Have I to change something else? Have I to create my own css for centering them vertically?

**Comment by mkhairi** [comment]
try check with latest release of materializecss.
see the example demo app.
closing old issue.
