### ISSUE TITLE
Simple form as: :select does not work 

### ISSUE THREAD

**Issue by jeremiahlukus** [mkhairi/materialize-sass#157]
I have used the js initializer at the top of my file, however, I am unable to get this to work.

`= f.association :tutor, collection: Tutor.all, label_method: :name, value_method: :id, as: :select`

Is there a work around to get the select, menu to work or disable the materialize css for only select?

**Comment by basicBrogrammer** [comment]
Have you tried https://github.com/jamesfwz/materialize-form?

**Comment by jeremiahlukus** [comment]
Yes, it doesn't work on select options.

**Comment by basicBrogrammer** [comment]
oooo yeah did you initialize it with javascript `$(input selector)..material_select();`
