### ISSUE TITLE
[1.0.0.alpha1] Side nav doesn't work with turbolinks 5.0.1

### ISSUE THREAD

**Issue by guilpejon** [mkhairi/materialize-sass#166]
I discovered this issue when I was trying to upgrade to materialize 1.0.0.alpha1, and I managed to create a sample app showing the issue.

You can find the sample app right [here](https://github.com/guilpejon/materialize_turbolinks_issue)

To reproduce the error with the sample app do the following:
1. Download the code and run `rails s`
2. Click the menu icon on the left of the navbar to open the sidenav
3. Click on any of the links on the sidenav
4. Try to open the sidenav again by clicking the same icon from before
5. The sidenav won't open again because the page refreshes each time you click the icon

If you comment out the `//= require turbolinks` from the application.js file, it works as expected.

**Comment by mkhairi** [comment]
https://github.com/Dogfalo/materialize/issues/5396
