### ISSUE TITLE
Support v1.0.0-beta

### ISSUE THREAD

**Issue by Mavvie** [mkhairi/materialize-sass#172]
Hey,

Thanks for all the work on this gem!
I was wondering if you have a timeline for updating to v1.0.0-beta which came out yesterday (see [materializecss.com](http://materializecss.com/)), or if there's any guide on how to open a PR that does the update if you're busy?

Thanks again!

**Comment by mkhairi** [comment]
@Mavvie Sorry for delayed update. v1.0.0.beta published.

**Comment by Mavvie** [comment]
Thanks, you rock!
