### ISSUE TITLE
helper-text styling is off

### ISSUE THREAD

**Issue by donBigote** [mkhairi/materialize-sass#173]
```
<div class="input-field col s12">
    <input id="email" type="email" class="validate">
    <label for="email">Email</label>
    <span class="helper-text" data-error="wrong" data-success="right">Helper text</span>
</div>
```
is giving this result:
<img width="482" alt="screen shot 2018-03-28 at 10 36 18 pm" src="https://user-images.githubusercontent.com/5143443/38070296-7f9cedb0-32d8-11e8-8d05-cc4aacd854f1.png">

It may be a problem.

**Comment by mkhairi** [comment]
Hi, i can't reproduce this issue.
I seem ok on this example http://materialize.labs.my/forms

**Comment by donBigote** [comment]
I had the old one installed
`gem 'materialize-sass'`
