### ISSUE TITLE
JavaScript evens are not initialized since 1.0.0-alpha.1

### ISSUE THREAD

**Issue by tricknotes** [mkhairi/materialize-sass#174]
The event handlers for initialization are replaced by 91b3f601e1afffbd5c7761812154a276fcd96373 due to turbolinks friendly.
However Materialize 1.0.0 doesn't recognize this event format.
In previous Materialize version, `$` was jQuery object but now it is [`cach`](https://github.com/Dogfalo/materialize/blob/21749fa/js/cash.js#L90) object.
- https://github.com/Dogfalo/materialize/blob/21749fa/js/cash.js#L90

This change has landed on 1.0.0-alpha.1.
- https://github.com/Dogfalo/materialize/commit/ea8fe2889fddf2ef7e1d348e236721608c0846ba#diff-db3c9f4552077510a5ee630c27d42f3f

**Comment by tricknotes** [comment]
I avoid this issue using materialize via yarn.

----

``` sh
$ yarn add materialize-css@next
```

``` ruby
# config/initializers/assets.rb
Rails.application.config.assets.paths << Rails.root.join('node_modules')
```

and the following changes:
``` diff
diff --git a/app/assets/javascripts/application.js b/app/assets/javascripts/application.js
index 4c2840f..b883b74 100644
--- a/app/assets/javascripts/application.js
+++ b/app/assets/javascripts/application.js
@@ -1,3 +1,3 @@
-//= require materialize-sprockets
+//= require materialize-css/dist/js/materialize
```

``` diff
diff --git a/app/assets/stylesheets/application.scss b/app/assets/stylesheets/application.scss
index b04947c..6b2bca1 100644
--- a/app/assets/stylesheets/application.scss
+++ b/app/assets/stylesheets/application.scss
@@ -1,8 +1,8 @@
-@import 'materialize';
+@import 'materialize-css/sass/materialize';
```

**Comment by kkarski82** [comment]
I can confirm that newer versions of materialize-sass aren't working correctly. The events are created during the first page visit but are lost when navigating away and coming back (I've checked and turbolinks picks it up fine, fires the initialization scripts but modals etc. are not working).

application.js
```javascript
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require materialize-sprockets
//= require_tree .
```

init.coffee
```coffeescript
window.App ||= {}

App.init = ->
  $('.button-collapse').sideNav()
  $('.dropdown-button').dropdown()
  $('.collapsible').collapsible()
  $('.tooltipped').tooltip({ delay: 50 })
  $('.modal').modal()
  $('select').material_select()

$(document).on('turbolinks:load', ->
  App.init()
)
```

Last working version of materialize sass is 0.97.8

**Comment by geniuskidkanyi** [comment]
one thing you can do is reset the count before initializing it.
