### ISSUE TITLE
Why no helpers?

### ISSUE THREAD

**Issue by a7madx7** [mkhairi/materialize-sass#177]
Why don't you create application helpers to make different HTML fragments the materialize way? Instead of this mess.

**Comment by bo-oz** [comment]
I created a small helper library that builds on the embedded SASS by this gem: https://github.com/bo-oz/materialize-components

**Comment by mkhairi** [comment]
i don't have time for this. slim/haml already do the job. Btw, pull requests are welcome. cheers ✌️
