### ISSUE TITLE
page:load

### ISSUE THREAD

**Issue by paulomcnally** [mkhairi/materialize-sass#18]
Turbolinks requiere ready and page:load events.

**Comment by paulomcnally** [comment]
https://vid.me/khfV <- Bug

**Comment by xamenrax** [comment]
@paulomcnally , did you try `https://github.com/kossnocorp/jquery.turbolinks` gem?

**Comment by mkhairi** [comment]
i think this behavior happen when you applied  "waves-effect" class on input tag. In materialiezcss documentation, they already mentioned about submit button [here](http://materializecss.com/buttons.html)

**Comment by mkhairi** [comment]
about wave effect die on turbolink page change, reinitialize the wave effect js should be fix the issue.
this turbolink compatibility should be issued at official materialize repo for further improvement.
```
$(document).on 'ready page:change', ->
	Waves.displayEffect()
```

**Comment by paulomcnally** [comment]
@xamenrax I added gem file now, but what code i need to recreate effect?

@mkhairi This code don't work for me.

![Img](http://i.imgur.com/IuF0aeR.png)

**Comment by mkhairi** [comment]
i guess you still use input tag with waves-effect right?
try change the submit button to 
```
  <button class="btn waves-effect waves-light" type="submit" name="action">Submit
    <i class="mdi-content-send right"></i>
  </button>
```
