### ISSUE TITLE
$map: #007bff is not a map for `map-has-key'

### ISSUE THREAD

**Issue by PavanOnRails** [mkhairi/materialize-sass#180]
Using `Rails 5.0.0` and trying to integrate `gem 'materialize-sass', '~> 1.0.0.rc2'` into my application, but the app broke with the below error

> $map: #007bff is not a map for `map-has-key'

Steps:

1. Added `gem 'materialize-sass', '~> 1.0.0.rc2'` into `Gemfile` and done `bundle install`
2. Added

```
@import "materialize/components/color-variables";
$primary-color: color("blue", "lighten-2") !default;
$secondary-color: color("yellow", "base") !default;
@import 'materialize';
```

into my `application.css.scss`

3. Added `//= require materialize-sprockets` to `application.js`
4. Restarted the server and when the app loaded, it broke with that error

Any help is appreciated, TIA

**Comment by mkhairi** [comment]
i'm using the same code in the [demo](http://materialize.labs.my), and suppose this works fine..
see: [application.scss](https://github.com/mkhairi/materialize-rails/blob/f8afef10d3fadebcd900b4de74a4a881106db718/app/assets/stylesheets/application.scss#L3-L6)

**Comment by PavanOnRails** [comment]
Hi @mkhairi Sorry for the late response. I'm sure its the problem with materialize content in the `application.css.scss`. I even checked by removing the materialize content from my `application.css.scss` and my app works fine.

**Comment by PavanOnRails** [comment]
I've updated the gem to `1.0.0` but the error persists. If I remove 

```
$primary-color: color("blue", "lighten-2") !default;
$secondary-color: color("yellow", "base") !default;
```
from application.css.scss, I've a new error which says
`Invalid CSS after ".blue.": expected class name, was "#007bff"`

**Comment by mkhairi** [comment]
@PavanOnRails, I'm pretty sure you are using with other CSS framework (eg: bootstrap) in your application.scss file. There is incompatibility issue if you multiple sass base framework sience they are using the same name sass mixins or function. Otherwise separate theme in different file.
