### ISSUE TITLE
Sidenav-overlay active with sidenav-fixed

### ISSUE THREAD

**Issue by louishugens** [mkhairi/materialize-sass#181]
Hello guys,

I use the sidenav-fixed class to have a fixed nav in the left of the screen but when i click any link in the nav it only the overlay that is activated. The link is not redirecting to the new page at all. Please help.

Thanks

**Comment by mkhairi** [comment]
hi @louishugens, you can try see the demo example [here](https://github.com/mkhairi/materialize-rails).

**Comment by louishugens** [comment]
Thanks @mkhairi, I have been trying to initialize it with jquery, is there an issue with that?

**Comment by mkhairi** [comment]
@louishugens, im not sure about that, but they already state in documentation about limitation jquery method

> Because jQuery is no longer a dependency, all the methods are called on the plugin instance.
   jQuery Method Calls
    You can still use the old jQuery plugin method calls.
    But you won't be able to access instance properties.

    $('.sidenav').sidenav('methodName');
    $('.sidenav').sidenav('methodName', paramName);
