### ISSUE TITLE
Navbar module not working....

### ISSUE THREAD

**Issue by iarobinson** [mkhairi/materialize-sass#183]
From my development experience, the materialize-sass gem doesn't load the JavaScript properly.

Specifically, the navbar module doesn't work.

Here is a screenshot of a brand new app with the [materialize gem installed as per the documentation](https://github.com/mkhairi/materialize-sass), and a [navbar which is copied directly from the Bootstrap documentation](https://getbootstrap.com/docs/4.0/components/navbar/#responsive-behaviors). 

## Mobile view:

<img width="603" alt="screen shot 2018-10-26 at 12 55 12 pm" src="https://user-images.githubusercontent.com/7991933/47589687-c0b2f500-d91e-11e8-8b78-dd5aec00fc12.png">

## Desktop view:

<img width="741" alt="screen shot 2018-10-26 at 12 55 16 pm" src="https://user-images.githubusercontent.com/7991933/47589688-c14b8b80-d91e-11e8-91f6-0aabab9533a1.png">

I can confirm materialize, jQuery and bootstrap are all loaded. Therefore, I'm guessing it's an issue with the sequence in which they are loaded. I feel it's likely related to how Rails loads them.

Thoughts?

**Comment by mkhairi** [comment]
Hi @iarobinson, materializecss is not base on bootstrap framework. you should refer official [materilaizecss documentation](https://materializecss.com/navbar.html) instead. not bootstrap.

**Comment by mkhairi** [comment]
if you looking bootstrap base material design, take a look at this gem [material-sass](https://github.com/mkhairi/material-sass).
