### ISSUE TITLE
update materialize.js

### ISSUE THREAD

**Issue by blacklist-arcc** [mkhairi/materialize-sass#187]
The components habe been updated but the file materialize.js has been ignored. This will broke e.g. the dropdown item on all rails setups using "//= require materialize".

**Comment by jkufro** [comment]
We are having the same issue with dropdowns and datepickers. There was a [PR merged into Materialize](https://github.com/Dogfalo/materialize/pull/6339) a few days ago for correcting both of these issues that hasn't been pulled into this repo yet.
