### ISSUE TITLE
Issues with Sass Files list in the colors.scss file

### ISSUE THREAD

**Issue by Tschuky101** [mkhairi/materialize-sass#21]
Every time I try to compile the SCSS files I am get this error message: 

error style.scss (Line 11 of _color.scss: Invalid CSS after " 'lighten-5'": expected ")", was ": #fdeaeb,")

**Comment by vinnygf** [comment]
@Tschuky101 Hi, how did you solve this ? I'm getting the same error.

**Comment by vinnygf** [comment]
@Tschuky101 I found the answer in issue #35 . Thanks
Use 'sass-rails', '~> 5.0' ... for anyone else who comes here.
