### ISSUE TITLE
Compatibility with Rails-like tools

### ISSUE THREAD

**Issue by simonc** [mkhairi/materialize-sass#24]
Hi,

Thanks for this awesome gem :)
One little thing though, I tried to use it outside of Rails (with Middleman) like I'm used to with bootstrap-sass and it didn't work because of a really strong dependency on Rails.
Do you think it would be possible at some point to decouple it a bit from Rails? :)

Cheers,

**Comment by xamenrax** [comment]
@simonc Can you provide some dummy repo with middleman and materialize-sass?

**Comment by simonc** [comment]
@xamenrax is this enough? :) https://github.com/simonc/middleman-materialize

**Comment by xamenrax** [comment]
@simonc Yup, thx, wiil take a look as soon as possible

**Comment by mkhairi** [comment]
@simonc can you test with latest update?

**Comment by simonc** [comment]
@mkhairi @xamenrax it works like a charm :D You're awesome! I updated the repo to add a js example too.
