### ISSUE TITLE
Waves bugged with turbolinks

### ISSUE THREAD

**Issue by TonGarcia** [mkhairi/materialize-sass#27]
Hi guys.
The waves effect, which use JS, is crashing while using turbolinks.
Even with jquery.turbolinks it is still bugged.
I suggest it as a bug for the materializecss team, could help me working on it?
Thanks.

**Comment by mkhairi** [comment]
Hi @TonGarcia  
What do you mean by crash?

if you using turbolink, try put this js code below to recreate effect on turbolink load

coffe script:
```coffee
$(document).on 'ready page:change', ->
    Waves.displayEffect()
```
or 

javascript:
```javascript
$(document).on('ready page:change', function() {
  Waves.displayEffect();
});
```

**Comment by TonGarcia** [comment]
Yeah, I´ve found it on the Gist/Gitter... could I or even You add it to the GEM project as a aux/fixes.js on the app/assets folder on the GEM dir. Couldn't you?

Thanks a lot for you answer. Have a nice day!
