### ISSUE TITLE
global vars not recognized / _variables.scss not working

### ISSUE THREAD

**Issue by rrphotosoft** [mkhairi/materialize-sass#28]
HI,
I Just installed your gem in my rails 4.2 app.
The stylesheet/fonts/javascripts work correctly.
However, I am unable to override the primary color or any other variables by mentioning them in a _variables.scss file which I then import into my application.scss file.
I'd appreciate any help.
Trying to debug, I got rid of the _variables.scss file completely and simply added the following lines at the top of my application.scss file:

$primary-color: color("blue", "lighten-2") !default;
@import 'materialize';

This doesn't work either.

-----------------------_variables.scss attempt----------------
application.scss
@import 'materialize';
@import '_variables';

_variables.scss
$primary-color: color("blue", "lighten-2") !default;

-----------------

I also tried removing the '!default', but that does not work either.

Regards,
RR.

PS: great work putting this gem together.

**Comment by mkhairi** [comment]
hi @rrphotosoft, 

Since color component variable are declare in _color.scss  you should import the color.scss first.
 you can overide color variable just like this
```scss
@import "materialize/components/color";
$primary-color: color("blue", "lighten-2") !default;
@import 'materialize';
```
or

you can import each component just like in this file below
https://github.com/mkhairi/materialize-sass/blob/master/app/assets/stylesheets/materialize.scss

**Comment by rrphotosoft** [comment]
@mkhairi ,
Hi, Thanks for the solution!
I am closing the issue.
Maybe you can add this to the gem documentation/readme?
Best Regards,
RR.
