### ISSUE TITLE
#issue media queries not working on mobile

### ISSUE THREAD

**Issue by FabianShallari** [mkhairi/materialize-sass#32]
Media queries are not working on mobile .

can someone tell me why is this happening?

![screen shot 2015-05-05 at 00 23 35](https://cloud.githubusercontent.com/assets/6090301/7463823/0cb8f9aa-f2bd-11e4-97a7-862ac51d5d73.png)

**Comment by FabianShallari** [comment]
Solved!

If anyone else has the issue just add this meta tag to your main layout:

<meta name="viewport" content="width=device-width" />

**Comment by Louisq12** [comment]
Having the same issue, can I see the meta tag @FabianShallari
