### ISSUE TITLE
Illegal nesting: Only properties may be nested beneath properties.

### ISSUE THREAD

**Issue by josephbridgwaterrowe** [mkhairi/materialize-sass#34]
I am receiving the error above when trying to visit my site using materialize-sass (it also does it with the bower package)

```
materialize-sass (0.96.2) app/assets/stylesheets/materialize/components/_prefixer.scss, line 54
materialize-sass (0.96.2) app/assets/stylesheets/materialize.scss, line 4
app/assets/stylesheets/application.scss, line 1
```

```ruby
# app/assets/stylesheets/application.scss
@import "materialize";
```

```ruby
# app/views/layouts/application.html.erb
<%= stylesheet_link_tag "application", :media => "all" %>
```

I'm sure I must be missing something silly.

Any help would be appreciated.

Thanks.

**Comment by mkhairi** [comment]
hi @josephbridgwaterrowe, check your gem sass-rails version. try use latest version of sass-rails.

**Comment by xamenrax** [comment]
@josephbridgwaterrowe , is this till an issue?

**Comment by josephbridgwaterrowe** [comment]
@xamenrax,

I believe that it is, but I haven't checked since Saturday... has anything changed since the weekend?

@mkhairi,

Here is the sass-rails version from my Gemfile.lock.

```
    sass (3.4.13)
    sass-rails (5.0.3)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (~> 1.1)
```

**Comment by mkhairi** [comment]
@josephbridgwaterrowe, did you included scss-lint gem?. It seems like scss-lint break the materialize sass syntax.
try remove the gem scss_lint from your Gemfile or
```
gem 'scss_lint', require: false
```
Hope that helps.

**Comment by josephbridgwaterrowe** [comment]
@mkhairi 

Thank you, I will try this next time I sit down with it and let you know how goes.

**Comment by FlowerWrong** [comment]
@mkhairi Thanks very much, it is work for me!

**Comment by josephbridgwaterrowe** [comment]
I'm looking forward to trying it again! Thanks guys!

**Comment by josephbridgwaterrowe** [comment]
:+1: I can confirm that this works for me too!

Thanks again.

**Comment by mkhairi** [comment]
:thumbsup:

**Comment by webzorg** [comment]
Same here, that worked. weird error.

**Comment by bhfmts** [comment]
I ran into the same error and none of the options above worked :/
I thought the "require: false" was going to work but it didn't. 
What it worked for me was installing the [linter-scss][1] plugin for Atom. After  I installed, I compiled again and it worked. I hope it works for you too guys. 
Regards, Bernardo.


  [1]: https://atom.io/packages/linter-scss-lint
