### ISSUE TITLE
Error trying to use materialize-sass

### ISSUE THREAD

**Issue by razy69** [mkhairi/materialize-sass#35]
Hi !

I don't know if it's a miss config from myself but i experience some bugs.

## Config 

- Cloud9
- Ruby : ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
- RVM : rvm 1.26.9 (1.26.9)
- Rails : Rails 4.1.6

## Gemfile 

gem 'rails', '4.1.6'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'materialize-sass'

## Custom.scss

@import "materialize";

## Error

> Invalid CSS after "  "lighten-5"": expected ")", was ":  #fdeaeb,"
  (in /home/ubuntu/workspace/events4.me/app/assets/stylesheets/custom.scss:11)

## Stack trace

> materialize-sass (0.95.2) app/assets/stylesheets/materialize/components/_color.scss:11
materialize-sass (0.95.2) app/assets/stylesheets/materialize.scss:6
app/assets/stylesheets/custom.scss:1
sass (3.2.19) lib/sass/scss/parser.rb:1147:in `expected'
sass (3.2.19) lib/sass/script/lexer.rb:206:in `expected!'
sass (3.2.19) lib/sass/script/parser.rb:483:in `assert_tok'
sass (3.2.19) lib/sass/script/parser.rb:433:in `paren'
sass (3.2.19) lib/sass/script/parser.rb:418:in `special_fun'
sass (3.2.19) lib/sass/script/parser.rb:413:in `raw'
sass (3.2.19) lib/sass/script/parser.rb:337:in `funcall'
sass (3.2.19) lib/sass/script/parser.rb:319:in `ident'
sass (3.2.19) lib/sass/script/parser.rb:228:in `unary_not'
sass (3.2.19) lib/sass/script/parser.rb:228:in `unary_div'
sass (3.2.19) lib/sass/script/parser.rb:228:in `unary_minus'
sass (3.2.19) lib/sass/script/parser.rb:228:in `unary_plus'
sass (3.2.19) lib/sass/script/parser.rb:209:in `times_div_or_mod'
sass (3.2.19) lib/sass/script/parser.rb:209:in `plus_or_minus'
sass (3.2.19) lib/sass/script/parser.rb:209:in `relational'
sass (3.2.19) lib/sass/script/parser.rb:209:in `eq_or_neq'
sass (3.2.19) lib/sass/script/parser.rb:209:in `and_expr'
sass (3.2.19) lib/sass/script/parser.rb:209:in `or_expr'
sass (3.2.19) lib/sass/script/parser.rb:298:in `space'
sass (3.2.19) lib/sass/script/parser.rb:283:in `interpolation'
sass (3.2.19) lib/sass/script/parser.rb:246:in `expr'
sass (3.2.19) lib/sass/script/parser.rb:477:in `assert_expr'
sass (3.2.19) lib/sass/script/parser.rb:49:in `parse'
sass (3.2.19) lib/sass/scss/parser.rb:1022:in `sass_script'
sass (3.2.19) lib/sass/scss/parser.rb:514:in `variable'
sass (3.2.19) lib/sass/scss/parser.rb:553:in `block_child'
sass (3.2.19) lib/sass/scss/parser.rb:543:in `block_contents'
sass (3.2.19) lib/sass/scss/parser.rb:82:in `stylesheet'
sass (3.2.19) lib/sass/scss/parser.rb:27:in `parse'
sass (3.2.19) lib/sass/engine.rb:342:in `_to_tree'
sass (3.2.19) lib/sass/engine.rb:274:in `to_tree'
sass (3.2.19) lib/sass/tree/visitors/perform.rb:225:in `visit_import'
sass (3.2.19) lib/sass/tree/visitors/base.rb:37:in `visit'
sass (3.2.19) lib/sass/tree/visitors/perform.rb:100:in `visit'
sass (3.2.19) lib/sass/tree/visitors/perform.rb:227:in `block in visit_import'
sass (3.2.19) lib/sass/tree/visitors/perform.rb:227:in `map'
sass (3.2.19) lib/sass/tree/visitors/perform.rb:227:in `visit_import'
sass (3.2.19) lib/sass/tree/visitors/base.rb:37:in `visit'
sass (3.2.19) lib/sass/tree/visitors/perform.rb:100:in `visit'
sass (3.2.19) lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
sass (3.2.19) lib/sass/tree/visitors/base.rb:53:in `map'
sass (3.2.19) lib/sass/tree/visitors/base.rb:53:in `visit_children'
sass (3.2.19) lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
sass (3.2.19) lib/sass/tree/visitors/perform.rb:121:in `with_environment'
sass (3.2.19) lib/sass/tree/visitors/perform.rb:108:in `visit_children'
sass (3.2.19) lib/sass/tree/visitors/base.rb:37:in `block in visit'
sass (3.2.19) lib/sass/tree/visitors/perform.rb:128:in `visit_root'
sass (3.2.19) lib/sass/tree/visitors/base.rb:37:in `visit'
sass (3.2.19) lib/sass/tree/visitors/perform.rb:100:in `visit'
sass (3.2.19) lib/sass/tree/visitors/perform.rb:7:in `visit'
sass (3.2.19) lib/sass/tree/root_node.rb:20:in `render'
sass (3.2.19) lib/sass/engine.rb:315:in `_render'
sass (3.2.19) lib/sass/engine.rb:262:in `render'
sass-rails (4.0.5) lib/sass/rails/template.rb:22:in `evaluate'
tilt (1.4.1) lib/tilt/template.rb:103:in `render'
sprockets (2.12.3) lib/sprockets/context.rb:197:in `block in evaluate'
sprockets (2.12.3) lib/sprockets/context.rb:194:in `each'
sprockets (2.12.3) lib/sprockets/context.rb:194:in `evaluate'
sprockets (2.12.3) lib/sprockets/processed_asset.rb:12:in `initialize'
sprockets (2.12.3) lib/sprockets/base.rb:374:in `new'
sprockets (2.12.3) lib/sprockets/base.rb:374:in `block in build_asset'
sprockets (2.12.3) lib/sprockets/base.rb:395:in `circular_call_protection'
sprockets (2.12.3) lib/sprockets/base.rb:373:in `build_asset'
sprockets (2.12.3) lib/sprockets/index.rb:94:in `block in build_asset'
sprockets (2.12.3) lib/sprockets/caching.rb:58:in `cache_asset'
sprockets (2.12.3) lib/sprockets/index.rb:93:in `build_asset'
sprockets (2.12.3) lib/sprockets/base.rb:287:in `find_asset'
sprockets (2.12.3) lib/sprockets/index.rb:61:in `find_asset'
sprockets (2.12.3) lib/sprockets/processed_asset.rb:111:in `block in resolve_dependencies'
sprockets (2.12.3) lib/sprockets/processed_asset.rb:105:in `each'
sprockets (2.12.3) lib/sprockets/processed_asset.rb:105:in `resolve_dependencies'
sprockets (2.12.3) lib/sprockets/processed_asset.rb:97:in `build_required_assets'
sprockets (2.12.3) lib/sprockets/processed_asset.rb:16:in `initialize'
sprockets (2.12.3) lib/sprockets/base.rb:374:in `new'
sprockets (2.12.3) lib/sprockets/base.rb:374:in `block in build_asset'
sprockets (2.12.3) lib/sprockets/base.rb:395:in `circular_call_protection'
sprockets (2.12.3) lib/sprockets/base.rb:373:in `build_asset'
sprockets (2.12.3) lib/sprockets/index.rb:94:in `block in build_asset'
sprockets (2.12.3) lib/sprockets/caching.rb:58:in `cache_asset'
sprockets (2.12.3) lib/sprockets/index.rb:93:in `build_asset'
sprockets (2.12.3) lib/sprockets/base.rb:287:in `find_asset'
sprockets (2.12.3) lib/sprockets/index.rb:61:in `find_asset'
sprockets (2.12.3) lib/sprockets/bundled_asset.rb:37:in `init_with'
sprockets (2.12.3) lib/sprockets/asset.rb:24:in `from_hash'
sprockets (2.12.3) lib/sprockets/caching.rb:54:in `cache_asset'
sprockets (2.12.3) lib/sprockets/index.rb:93:in `build_asset'
sprockets (2.12.3) lib/sprockets/base.rb:287:in `find_asset'
sprockets (2.12.3) lib/sprockets/index.rb:61:in `find_asset'
sprockets (2.12.3) lib/sprockets/environment.rb:75:in `find_asset'
sprockets (2.12.3) lib/sprockets/base.rb:295:in `[]'
sprockets-rails (2.3.1) lib/sprockets/rails/helper.rb:243:in `lookup_asset_for_path'
sprockets-rails (2.3.1) lib/sprockets/rails/helper.rb:203:in `check_errors_for'
sprockets-rails (2.3.1) lib/sprockets/rails/helper.rb:172:in `block in stylesheet_link_tag'
sprockets-rails (2.3.1) lib/sprockets/rails/helper.rb:171:in `map'
sprockets-rails (2.3.1) lib/sprockets/rails/helper.rb:171:in `stylesheet_link_tag'
app/views/layouts/application.html.erb:5:in `_app_views_layouts_application_html_erb__2272114930655414386_42727100'
actionview (4.1.6) lib/action_view/template.rb:145:in `block in render'
activesupport (4.1.6) lib/active_support/notifications.rb:161:in `instrument'
actionview (4.1.6) lib/action_view/template.rb:339:in `instrument'
actionview (4.1.6) lib/action_view/template.rb:143:in `render'
actionview (4.1.6) lib/action_view/renderer/template_renderer.rb:67:in `render_with_layout'
actionview (4.1.6) lib/action_view/renderer/template_renderer.rb:53:in `render_template'
actionview (4.1.6) lib/action_view/renderer/template_renderer.rb:17:in `render'
actionview (4.1.6) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (4.1.6) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (4.1.6) lib/action_view/rendering.rb:99:in `_render_template'
actionpack (4.1.6) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (4.1.6) lib/action_view/rendering.rb:82:in `render_to_body'
actionpack (4.1.6) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
actionpack (4.1.6) lib/action_controller/metal/renderers.rb:32:in `render_to_body'
actionpack (4.1.6) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (4.1.6) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (4.1.6) lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
activesupport (4.1.6) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
activesupport (4.1.6) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (4.1.6) lib/action_controller/metal/instrumentation.rb:41:in `block in render'
actionpack (4.1.6) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
activerecord (4.1.6) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
actionpack (4.1.6) lib/action_controller/metal/instrumentation.rb:40:in `render'
app/controllers/pages_controller.rb:4:in `index'
actionpack (4.1.6) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.1.6) lib/abstract_controller/base.rb:189:in `process_action'
actionpack (4.1.6) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.1.6) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.1.6) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.6) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.6) lib/active_support/callbacks.rb:229:in `block in halting'
activesupport (4.1.6) lib/active_support/callbacks.rb:229:in `call'
activesupport (4.1.6) lib/active_support/callbacks.rb:229:in `block in halting'
activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.6) lib/active_support/callbacks.rb:86:in `call'
activesupport (4.1.6) lib/active_support/callbacks.rb:86:in `run_callbacks'
actionpack (4.1.6) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.1.6) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.1.6) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
activesupport (4.1.6) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.1.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.1.6) lib/active_support/notifications.rb:159:in `instrument'
actionpack (4.1.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.1.6) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.1.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.1.6) lib/abstract_controller/base.rb:136:in `process'
actionview (4.1.6) lib/action_view/rendering.rb:30:in `process'
actionpack (4.1.6) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.1.6) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.1.6) lib/action_controller/metal.rb:232:in `block in action'
actionpack (4.1.6) lib/action_dispatch/routing/route_set.rb:82:in `call'
actionpack (4.1.6) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
actionpack (4.1.6) lib/action_dispatch/routing/route_set.rb:50:in `call'
actionpack (4.1.6) lib/action_dispatch/journey/router.rb:73:in `block in call'
actionpack (4.1.6) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.1.6) lib/action_dispatch/journey/router.rb:59:in `call'
actionpack (4.1.6) lib/action_dispatch/routing/route_set.rb:678:in `call'
rack (1.5.3) lib/rack/etag.rb:23:in `call'
rack (1.5.3) lib/rack/conditionalget.rb:25:in `call'
rack (1.5.3) lib/rack/head.rb:11:in `call'
actionpack (4.1.6) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.1.6) lib/action_dispatch/middleware/flash.rb:254:in `call'
rack (1.5.3) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.5.3) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.1.6) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.1.6) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.1.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
activerecord (4.1.6) lib/active_record/migration.rb:380:in `call'
actionpack (4.1.6) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.1.6) lib/active_support/callbacks.rb:82:in `run_callbacks'
actionpack (4.1.6) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.1.6) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.1.6) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
actionpack (4.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.1.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.1.6) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.1.6) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.1.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.1.6) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.1.6) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.1.6) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.1.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.3) lib/rack/methodoverride.rb:21:in `call'
rack (1.5.3) lib/rack/runtime.rb:17:in `call'
activesupport (4.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
rack (1.5.3) lib/rack/lock.rb:17:in `call'
actionpack (4.1.6) lib/action_dispatch/middleware/static.rb:64:in `call'
rack (1.5.3) lib/rack/sendfile.rb:112:in `call'
railties (4.1.6) lib/rails/engine.rb:514:in `call'
railties (4.1.6) lib/rails/application.rb:144:in `call'
rack (1.5.3) lib/rack/lock.rb:17:in `call'
rack (1.5.3) lib/rack/content_length.rb:14:in `call'
rack (1.5.3) lib/rack/handler/webrick.rb:60:in `service'
/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'

Thanks in advance and good luck :D

**Comment by mkhairi** [comment]
hi @razy69, you should update your 'sass-rails' gem to the latest version.
see https://github.com/mkhairi/materialize-sass/issues/6

**Comment by razy69** [comment]
Thanks it works !

I have to update my gemfile :

gem 'rails', '4.1.8'
gem 'sass-rails', '~> 5.0'

Then : bundle update

Nice !
