### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by ajm339** [mkhairi/materialize-sass#39]
The class labels for icons is not matching appropriately according to your guide (http://materializecss.com/icons.html).

For example, using class "mdi-navigation-apps" shows the icon for "mdi-navigation-fullscreen-exit".

Not sure if it is an issue with the original Sass file from MaterializeCSS or the gem install.  Posted an issue on both repos.

**Comment by mkhairi** [comment]
hi @ajm339, which gem version you are used?. I tested the icon that you mentioned, it look like ok to me.

**Comment by ajm339** [comment]
I am using  "materialize-sass 0.96.2".  I posted on the materializecss Github and another user is having the same issue.

https://github.com/Dogfalo/materialize/issues/1499#issuecomment-110765119

**Comment by ajm339** [comment]
Another example where it is off:

My navigation bar specifies the mobile "hamburger" menu icon:
<a href="#" data-activates="mobile" class="button-collapse"><i class="mdi-navigation-menu light-green-text text-darken-2"></i></a>

But I get this icon on Mobile:

![screen shot 2015-06-10 at 10 35 06 am](https://cloud.githubusercontent.com/assets/4138881/8085118/761d47f0-0f5c-11e5-9724-02eea205b88a.png)

**Comment by ajm339** [comment]
So when I removed your gem and referenced the CSS and JS from the MaterializeCSS CDN, the issue resolved itself....

Normally when a third-party gem installs CSS and JS files they are saved in vendor/assets however yours do not appear there.  Rails accesses the files from /assets/materialize however I cannot find where they actually lie within the application so that I could update the CSS and Font files manually.

Can you provide any insight on this? Thanks

**Comment by ajm339** [comment]
Seems it saves it all in the .rbenv gem folder.  Would appreciate newer version of gem to save it in the actual Rails application if possible for you.

**Comment by mkhairi** [comment]
Emmm.. This is weird. The icons look normal for my app. have a look on this sample rails apps deployed on heroku and used this gem. http://materialize-rails.herokuapp.com/

**Comment by mkhairi** [comment]
This gem contains an engine class which inherits from Rails::Engine. Rails is automatically informed that the directory for assets ```app/assets``` directories of this engine are added to the search path of Sprockets. [more on rails asset pipeline info](http://guides.rubyonrails.org/asset_pipeline.html#adding-assets-to-your-gems). If you want to bundle gem into you rails apps you can run ```bundle install --deployment```. that will install your bundle to the ```vendor/bundle``` directory.  [more on bundle install info](http://bundler.io/v1.9/bundle_install.html)

**Comment by ajm339** [comment]
Very odd, not sure why my app was having issues with locating the right icons then...

And thank you for the information in the second comment! Very helpful.
