### ISSUE TITLE
I use this gem with Rails 4.2.0 and Ruby 2.1.5, all is OK, but icons not showing, whats wrong ? Help me, please.

### ISSUE THREAD

**Issue by dim321** [mkhairi/materialize-sass#42]
h2 class="center light-blue-text"><i class="material-icons">flash_on</i></h2

![image](https://cloud.githubusercontent.com/assets/2948302/8423056/bbe1da60-1f0d-11e5-9e6e-f5b36c9268cd.png)

**Comment by dim321** [comment]
I add to head
link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
and icons show.

**Comment by Bickson** [comment]
This did not solve the problem for me, any ideas?

**Comment by mkhairi** [comment]
@Bickson see #45
