### ISSUE TITLE
Icons not working

### ISSUE THREAD

**Issue by nahtnam** [mkhairi/materialize-sass#44]
Hey!

I noticed the icons arent working.

EDIT: More info:
MDI seems to be installed here: https://github.com/mkhairi/materialize-sass/blob/master/app/assets/stylesheets/materialize/components/_icons-material-design.scss

But it doesnt work. Any idea whats going on? @mkhairi 

Thanks.

**Comment by mkhairi** [comment]
hi @nahtnam,
all icon should be work fine. here some sample http://materialize-rails.herokuapp.com.
If you notice at http://materializecss.com/icons.html, currently they are using new typographic feature called ligatures. You need include additional stylesheet from google if you want to use ligatures icon syntax.

**Comment by nahtnam** [comment]
That makes sense. Thank you.
