### ISSUE TITLE
icons

### ISSUE THREAD

**Issue by dottgonzo** [mkhairi/materialize-sass#45]
rails new apptest (ruby 2.2.1, rails 4.2)
add materialize-sass to Gemfile
add the require materialize-sprocklets to app/assets/application.js
add @import materialize; to app/assets/stylesheet.scss (and remove .css one)

everything works well, but icons don't work (in development mode). No errors is displayed from server or browser. If i try to use the cdn (<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">) icons works

what's wrong?

**Comment by mkhairi** [comment]
see #44
