### ISSUE TITLE
Some CSS is broken in rails

### ISSUE THREAD

**Issue by jabbajac** [mkhairi/materialize-sass#47]
I'm having some broken CSS when following your readme and trying to use it in rails. When and container under the nav ends up with 0px height and all ul and li used in the nav suddenly get the fonts messed up and sticking to the top of the navbar. See attached image looking at logout link on  

![image](https://cloud.githubusercontent.com/assets/5124266/8610486/a59b07d4-2680-11e5-8169-87406f089fab.png)

_topnav.html.erb
```
<nav class="top-nav">
      <a href="#" class="brand-logo">CAT</a>
      <ul class="right">
        <li><a href="#">Logout</a></li>
      </ul>
</nav>
```

application.scss
```
 *= require_tree .
 *= require_self
 */
@charset "UTF-8";

// Reset
@import "materialize/components/normalize";
@import "materialize/components/color";
$primary-color: color("blue", "accent-2") !default;

@import "materialize";


header, main, footer {
  padding-left: 240px;
}

@media only screen and (max-width : 992px) {
  header, main, footer {
    padding-left: 0;
  }
}
```

That should be the way to use materialize-css right?

**Comment by TomSchillemans** [comment]
I have the same problem with the dropdown menu and buttons.

![screen shot 2015-07-12 at 2 59 13 pm](https://cloud.githubusercontent.com/assets/3533733/8637872/96514a04-28a6-11e5-9b80-4e3267428dc8.png)

as you can see here, the dropdown-content is underneath the button and when I click on the button, I see a transparent dropdown menu and the list as it here disappears but like I said, no background color and nu highlight color. 

When I tried the materialize-css example in codepen it just works!

![Here's my coped example](http://codepen.io/anon/pen/oXdObO)

I converted it to HAML which I use like so:

```haml
%a{ :class => 'dropdown-button btn', :href => '#', :data => {:activates => 'dropdown1'} } Drop Me!

%ul{id: 'dropdown1', class: 'dropdown-dontent'}
  %li
    %a{href: '#!'} one
  %li
    %a{href: '#!'} two
  %li.divider
  %li
    %a{href: '#!'} three
```

**Comment by mkhairi** [comment]
i think you should add nav wrapper class.
```html

<nav class="top-nav">
     <div class="nav-wrapper">
         <a href="#" class="brand-logo">CAT</a>
         <ul class="right">
            <li><a href="#">Logout</a></li>
         </ul>
    </div>
</nav>

```

**Comment by jabbajac** [comment]
I tried that and it appears to still not be working. I just added some padding in the application.scss file for it. If there's anything else I can try please let me know. I'm a beginner with a lot of the front-end works in terms of css and how rails assets work so if I'm missing anything just let me know.

**Comment by mkhairi** [comment]
rails assets is just place where you should place your js and css file. The rest you should follow documentation on [materilizecss.com](http://materializecss.com/getting-started.html) and maintain html structure in views. If design in rails is hard for you, you should start with mockup structure design in basic html first, then use that working snippet in your rails apps.

**Comment by jabbajac** [comment]
The snippets I use work if I don't do it in rails and just mock up the page using CSS. It's once I move it into rails that I have this issue. I'll build out a another rails project in a few days for generic testing and see if I run into the same issues. I'll put that one on my github so that you can see what I'm trying to do and let me know if I'm doing something wrong. 

btw, thank you for taking the time to answer my questions. I really appreciate it!

**Comment by Kamasoutra** [comment]
Hi ! Did you figured out something special ? I'm having the same kind of trouble :cry:

**Comment by jabbajac** [comment]
Unfortunately no, I ended up  just adding CSS to overwrite and add the correct padding. I added the following in my application.scss

    .top-nav ul li a {
      padding: 1.54em
    }

That seems to have gotten the padding about right. It's not perfect...but for now it's good enough.

**Comment by Kamasoutra** [comment]
Hi ! Thanks for your answer ;)

In my case I just figured out whats caused me such trouble by fixing something else (a:visited making links grey instead of normal color). I simply deleted all the nasty css generated by scaffolding in scaffolds.scss and navbar went back to normal ! Maybe it can help you too.

**Comment by jabbajac** [comment]
Actually...that's what it was. I just had to get rid of most of what was in scaffolds.scss. I didn't even notice the file until you pointed it out.

**Comment by LuigiAlver** [comment]
@Kamasoutra your answered just saved me. I had been looking for what broke the navbar for almost 30 min. 
Thank you!

**Comment by Kamasoutra** [comment]
My pleasure ;)
