### ISSUE TITLE
Dropdown isn't working in Rails

### ISSUE THREAD

**Issue by TomSchillemans** [mkhairi/materialize-sass#48]
I have the same problem with the dropdown menu and buttons.

![screen shot 2015-07-12 at 2 59 13 pm](https://cloud.githubusercontent.com/assets/3533733/8637872/96514a04-28a6-11e5-9b80-4e3267428dc8.png)

as you can see here, the dropdown-content is underneath the button and when I click on the button, I see a transparent dropdown menu and the list as it here disappears but like I said, no background color and nu highlight color. 

When I tried the materialize-css example in codepen it just works!

[Here's my coped example](http://codepen.io/anon/pen/oXdObO)

I converted it to HAML which I use like so:

```haml
%a{ :class => 'dropdown-button btn', :href => '#', :data => {:activates => 'dropdown1'} } Drop Me!

%ul{id: 'dropdown1', class: 'dropdown-dontent'}
  %li
    %a{href: '#!'} one
  %li
    %a{href: '#!'} two
  %li.divider
  %li
    %a{href: '#!'} three
```

**Comment by mkhairi** [comment]
hi @TomSchillemans,  if you using turbolink you should reinitialize dropdown js on each page load
```coffee
$(document).on 'ready page:change', ->
        $('.dropdown-button').dropdown()
```
alternatively, you can use the [jquery.turbolink](https://github.com/kossnocorp/jquery.turbolinks) gem

**Comment by TomSchillemans** [comment]
Thanks for the update!

Does the jquery.turbolink gem do the same?

**Comment by mkhairi** [comment]
seem like there is typo here
```html
%ul{id: 'dropdown1', class: 'dropdown-content'}
```

**Comment by TomSchillemans** [comment]
Oh wow, yeah dang, haven't even seen that. But will that break the JS as well as the CSS of the dropdown?

**Comment by mkhairi** [comment]
yeah!

**Comment by TomSchillemans** [comment]
Ok, yeah that did the trick, I think together with the gem i installed.

Thanks for your help! Sorry I didn't see my own typo there! Thanks for pointing out. I am prone to over looking typo's. I should look out for them more often.
