### ISSUE TITLE
collection_select does not render without using browser-default class

### ISSUE THREAD

**Issue by Shawg** [mkhairi/materialize-sass#52]

**Comment by mkhairi** [comment]
hi @Shawg, can you provide more details on this matter

**Comment by nrbrookes** [comment]
Selects in general seem a bit broken. With the following bit of haml:

```haml
%form
  .row
    .input-field.col.s12
      %select.browser-default
        %option Option 1
        %option Option 2
        %option Option 3
      %label Browser default
      
  .row
    .input-field.col.s12
      %select
        %option Option 1
        %option Option 2
        %option Option 3
      %label Materialize style
```

The first select has a label which crashes into the select element, the second select isn't rendered at all.

![materialize-sass](https://cloud.githubusercontent.com/assets/8059371/9424506/a9da9bba-48e6-11e5-8825-c75e74d91dd3.png)

**Comment by nrbrookes** [comment]
Ahhh, I found a partial solution in http://stackoverflow.com/questions/28258106/materialize-css-select-doesnt-seem-to-render 

Selects aren't great in Materialize.
