### ISSUE TITLE
How to use 1 component?

### ISSUE THREAD

**Issue by simkessy** [mkhairi/materialize-sass#53]
What would I need to do if I just want to use 1 component, like your cards implementation, with my mainly bootstrap application? Is this something that's possible? I tried to import only the card component but I got an error about a missing variable. But if I import all, it breaks the site UI pretty much.

**Comment by mkhairi** [comment]
hi @simkessy , each single components may depend on variable, mixins, prefixer. you need to import this file first before import the component. but there is another hacky way by  declare the only missing variables or mixins manualy from source.

**Comment by simkessy** [comment]
Thanks, I was able to understand what was going on once I learned more about SASS. Awesome theme.
