### ISSUE TITLE
Modals not working in rails 4

### ISSUE THREAD

**Issue by jabbajac** [mkhairi/materialize-sass#54]
I'm trying to make a modal form pop up to add a new comment. 

HTML Snippet

```
<a href="#add_ac" data-toggle="modal" class="waves-effect waves-light blue accent-2 white-text btn">Add Comment</a>

<div id="add_ac" class="modal">
  <div class="modal_content">
    <%= render '/s_comments/form' %>
  </div>
</div>
```

I'm trying to use the link to trigger the modal

This is in the javascript file for the model (admin.js)
```
  $('.modal-trigger').leanModal({
    dismissible: true
  });
```

According to the materialize css documentation that should work. 

The following is in the headers for my application.js file
```
//= require jquery2
//= require jquery_ujs
//= require turbolinks
//= require materialize-sprockets
//= require_tree .
```

Thank you,
jabbajac

**Comment by mkhairi** [comment]
hi @jabbajac, seems like you miss the class "modal-trigger" for the button 

http://materialize-rails.herokuapp.com/components
