### ISSUE TITLE
Issue using materialize-sass with form_for

### ISSUE THREAD

**Issue by kumar91gopi** [mkhairi/materialize-sass#56]
![button](https://cloud.githubusercontent.com/assets/10248907/9674919/c06951a4-52f1-11e5-964e-f034ca3c6aba.JPG)
the button initially looks fine but in case of errors in the login form it changes to this.
![radio](https://cloud.githubusercontent.com/assets/10248907/9674920/c09c54f0-52f1-11e5-8035-327ad20345b2.JPG)
i am getting two sets of radio buttons and the materialise radio-buttons are not clickable the others are
i have facing many issues styling form_for with materialize-sass. 
please help :(

**Comment by mkhairi** [comment]
hi @kumar91gopi , When you use a button to submit a form, instead of using a input tag, use a button tag with a type submit

```
  <button class="btn waves-effect waves-light" type="submit" name="action">Submit
    <i class="material-icons">send</i>
  </button>
```

**Comment by kumar91gopi** [comment]
i am using the the inbuilt form__for generator how to specify button tag with f.submit?
here is my code:
 <div class="actions">
          <%= f.submit "Log in" ,class: "btn waves-effect waves-light"%>
        </div> 

also how to solve the problem with radio buttons:
here is the code for radio buttons:
 <div class="input-field">
        <%= f.radio_button :gender, 'm'%> 
        <%= label :gender, 'Male' %>
        <br/>
        <%= f.radio_button :gender, 'f'%>
        <%= label :gender, 'FEMALE' %>
        <br/>
        </div>

**Comment by mkhairi** [comment]
hi @kumar91gopi,  take a look of this snippet.

input button
```
 <div class="input-field col s3">
          <%= f.button class: "waves-effect waves-light btn ", type: :submit do %>
              Create < i class="material-icons right"> send </i>
          <%end%>
</div>
```

radio button
```
<%= f.radio_button :gender, "m"  %>
<%= f.label :gender_m, "Male" %>
<%= f.radio_button :gender, "f" %>
<%= f.label :gender_f, "Female" %>
```

hope this will helps you.

**Comment by kumar91gopi** [comment]
hi @mkhairi  , issue has been resolved .

thank you very much.
