### ISSUE TITLE
class 'material-icons' doesn't display icons 

### ISSUE THREAD

**Issue by seoyoochan** [mkhairi/materialize-sass#58]
I am using the following markup on my react-based app.
```
<div className="app">
        <nav className="light-blue lighten-1" role="navigation">
          <div className="nav-wrapper container">
            <a id="logo-container" href="#" className="brand-logo">Logo</a>
            <ul className="right hide-on-med-and-down">
              <li><a href="#">Navbar Link</a></li>
            </ul>
            <ul id="nav-mobile" className="side-nav">
              <li><a href="#">Navbar Link</a></li>
            </ul>
            <a href="#" data-activates="nav-mobile" className="button-collapse"><i className="material-icons">menu</i></a>
          </div>
        </nav>
        <div className="section no-pad-bot">
          <div className="container">
            <div className="row center">
              <div className="col s12 m12 l12">
                page content
              </div>
            </div>
          </div>
        </div>
      </div>
```

However, `<i className="material-icons">menu</i>` doesn't change to the stack bar icon on small screen. See the demo at http://materializecss.com/templates/starter-template/preview.html

I even added the following code on `application.scss`, but still not working.

```
.material-icons {
    font-family: 'Material-Design-Icons';
    font-weight: normal;
    font-style: normal;
    font-size: 24px;
    line-height: 1;
    letter-spacing: normal;
    text-transform: none;
    display: inline-block;
    word-wrap: normal;
    -webkit-font-feature-settings: 'liga';
    -webkit-font-smoothing: antialiased;
}
```

**Comment by mkhairi** [comment]
hi @seoyoochan, you need to add this in your layout 

```  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">```

ref: [materializecss.com/icons.html](http://materializecss.com/icons.html)

**Comment by seoyoochan** [comment]
@mkhairi  Is there a way to load them as local? I need to prepare for offline state development environment..

**Comment by mkhairi** [comment]
@seoyoochan, for the current version they still keep the local icon. you use local icon by use old syntax 
eg: ```<i class="mdi-action-accessibility"></i>```  
for icon class ref: [materialize-rails.herokuapp.com](http://materialize-rails.herokuapp.com/)

alternatively, you can try this gem [material_icons](https://github.com/Angelmmiguel/material_icons) :)
Cheers!

**Comment by seoyoochan** [comment]
@mkhairi  Thank you for sharing the link and your solution :+1:
