### ISSUE TITLE
Waves are not working in rails4

### ISSUE THREAD

**Issue by jvanbaarsen** [mkhairi/materialize-sass#59]
Somehow I can't get the Wave animation working in Rails4. I used the starter template, and even then the orange button is not showing the wave animation.

Is there something I'm doing wrong? Should I initialize Wave somewhere?

**Comment by mkhairi** [comment]
hi @jvanbaarsen, yes, you need initialize it first. see #27

**Comment by jvanbaarsen** [comment]
@mkhairi Thanks!
