### ISSUE TITLE
Javascript not working after navigating through links

### ISSUE THREAD

**Issue by YerkoPalma** [mkhairi/materialize-sass#61]
I discover this problem with the wave effect on buttons. First it wasn't working at all, so I discover [this issue](https://github.com/mkhairi/materialize-sass/issues/27) and added the initialization in one of my `.js` files in the assets folder.

So my waves were working on my index page, but when I click and navigate to any other page they just stop working. This happens also with my `tooltips` and `modals` so I assume that the problem is with the entire js file 

here is how I initialize my components

    $(document).on('ready', function() {
        Waves.displayEffect();
        $(".button-collapse").sideNav();
        $('.modal-trigger').leanModal();
    });

The version of my gems from `Gemfile.lock`

    materialize-sass (0.95.2)
          sass (~> 3.1)

Would this be a problem related with turbolinks? any help would be appreciated

**Comment by mkhairi** [comment]
hi @YerkoPalma,  if you using turbolink, you should  use add ```page:change ``` or ```page:load``` on function. It should be work. Maybe you missed load your initialized js file in application.js.

**Comment by YerkoPalma** [comment]
Hi @mkhairi, thanks that fixed a lot of problems, but I'm still having issues only with my tooltips, but I guess that problem belongs to another issue. Anyway, with this new fix I will check once again my tooltip so I don't have to open a new issue. Thanks again.
