### ISSUE TITLE
Sass::SyntaxError: Undefined variable: "$medium-and-up" and "$button-height"

### ISSUE THREAD

**Issue by jgrosso** [mkhairi/materialize-sass#65]
I'm getting the error 'Sass::SyntaxError: Undefined variable: "$medium-and-up"' and "$button-height" whenever I access a page or run 'rake assets:precompile'

My config/application.rb looks like this:
```
...
config.assets.enabled = true
config.assets.precompile = %w(*.js *.coffee *.scss *.css *.png *.jpg *.jpeg *.gif *.ico *.eot *.svg *.ttf *.woff)
...
```

My application.css.scss looks like this:
```
...
/*
 *= require_self
 */
@import "materialize/components/color";
$primary-color: color("blue", "lighten-2") !default;
@import "materialize";
...
```

In application.html.erb, application.css is imported before the controller-specific stylesheet which uses $medium-and-up.

**Comment by jgrosso** [comment]
Changing
```
config.assets.precompile = %w(... *.css ...)
```
to
```
config.assets.precompile = %w(... *.scss ...)
```
worked.

**Comment by mkhairi** [comment]
hi @jgrosso, you should remove any ```*= require``` in you scss file

**Comment by jgrosso** [comment]
Still doesn't work....
