### ISSUE TITLE
This is using the old icons format

### ISSUE THREAD

**Issue by rpierreye** [mkhairi/materialize-sass#66]
Can this be updated to the new font icons format?

According to the documentation on materializecss.com, this is the structure to create icons

```HTML
// i element with 'material-icons' class, with the name of the icon as the value. See example:
<i class="material-icons">menu</i>
```

However this gem seems to be using the old format, (or the font files aren't up to date): 

```HTML
<i class="mdi-navigation-arrow-drop-down"></i>
```

**Comment by mkhairi** [comment]
hi @rpierreye , for the new format you should include this in ```<head>```
```html
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> 
```
refer http://materializecss.com/icons.html
