### ISSUE TITLE
When switching between pages input elements are not rendered as 'active'.

### ISSUE THREAD

**Issue by mtuck063** [mkhairi/materialize-sass#69]
The cause is clearly turbolinks. When switching to my edit page, the page looks like this:

![image](https://cloud.githubusercontent.com/assets/6563469/11015861/5f66396c-853c-11e5-96d9-9123a8b50f3e.png)

But when I refresh the page, everything is fine:

![image](https://cloud.githubusercontent.com/assets/6563469/11015867/8be281ee-853c-11e5-8ec6-b6d6b1e73b07.png)

**Comment by mkhairi** [comment]
hi @mtuck063,  see #63 :)
