### ISSUE TITLE
My application does not work in production mode.

### ISSUE THREAD

**Issue by Fernandox64** [mkhairi/materialize-sass#74]
The javascript files look like they are not being compiled properly.
But it works in the way development.

Below my production.rb file
[production.txt](https://github.com/mkhairi/materialize-sass/files/43189/production.txt)

Thank you for spending your time here...

**Comment by mkhairi** [comment]
Hi @Fernandox64 , Have you compiled the assets yet?

run ``` RAILS_ENV=production bundle exec rake assets:precompile ```

then restart server.

**Comment by Fernandox64** [comment]
Thank you @mkhairi  for help...
