### ISSUE TITLE
tooltips not appearing in the right place 

### ISSUE THREAD

**Issue by elena-vi** [mkhairi/materialize-sass#75]
When I hover over the icon, a tool tip saying "help" should appear underneath it, but for some strange reason it doesn't. See screenshot for how the tooltip appears and the HTML of how it's inserted, *the tooltip scss hasn't been messed with*

![screenshot from 2015-11-27 15 33 07](https://cloud.githubusercontent.com/assets/8051117/11444320/67a634d4-951c-11e5-9428-2240cd571918.png)

**Comment by mkhairi** [comment]
@elena-vi, sorry, i am not sure about that.  this should be related with another css definition.  Have you tried use materializecss form official source/cdn?
