### ISSUE TITLE
Roboto font problem

### ISSUE THREAD

**Issue by lebart** [mkhairi/materialize-sass#76]
Hi, 

I was just playing around with this gem and I noticed that after I've installed it on a new rails app then @import "materialize", the Roboto font doesn't work as it supposed. 

I just made a simple `<strong>test</strong>` and I see that the font weight doesn't work. 

If I load materialize from the CDN it's working. 
If I load the font from Google it's working. 

What is strange is with the gem the font seems to be loaded and the path seems fine but it's not putting the font as it supposed to be. 

As I can see on the fresh install, only the regular roboto font is imported

Any idea?

**Comment by lebart** [comment]
I think I find the problem. 

In the original source: https://github.com/Dogfalo/materialize/blob/master/sass/components/_roboto.scss

The font-family property isn't the same then in your components/_roboto.scss file. 

I try changing the font-family and it seems to be working fine.

**Comment by mkhairi** [comment]
@lebart, thanks for reporting. Sorry for that.  This changed due  from #67 pr.  I will revert this changes.

**Comment by lebart** [comment]
Thank you. 

I see the pr but I don't understand why did he change the font name. When you take the Roboto font from Google font directly, they just give you different font weight but name it the same way. It's easier to use.

BTW thanks for maintaining this gem.
