### ISSUE TITLE
Problem with Mixins

### ISSUE THREAD

**Issue by Nkadze** [mkhairi/materialize-sass#77]
Hi, I'm trying to use Prefixer feature of Materialize, so as it's said on their official site I added 
```scss
 @include transition(.3s);
```
in my custom .scss file which is imported at the bottom of my application,
but I get error: Undefined mixin 'transition'.
I imported:
 "materialize/components/mixins", 
"materialize/components/variables" and 
"materialize/components/prefixer" 
but nothing changed

**Comment by mkhairi** [comment]
hi @Nkadze,
See https://github.com/Dogfalo/materialize/pull/2271 
Seems like they comment out all prefixer and mixins code and use Autoprefixer.

**Comment by Nkadze** [comment]
Thanks @mkhairi 
That's solution to my problem
