### ISSUE TITLE
problem with font and icons

### ISSUE THREAD

**Issue by DRAKUN** [mkhairi/materialize-sass#78]
hi i ve an problem to view icon dropdown menu
![capture d ecran 2016-01-02 a 00 32 16](https://cloud.githubusercontent.com/assets/366065/12072750/5c5b25a2-b0e8-11e5-9a12-c66b1c73237c.png)
![capture d ecran 2016-01-02 a 00 32 18](https://cloud.githubusercontent.com/assets/366065/12072751/5c919c40-b0e8-11e5-89e1-b40d7c2c6138.png)

thanks

**Comment by mkhairi** [comment]
hi @DRAKUN , you must include this in  ```<head>``` layout
```html
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

```


see [materializecss.com/icons](http://materializecss.com/icons.html) .

**Comment by DimasJok** [comment]
but you need internet... not is a solution

**Comment by mkhairi** [comment]
@DimasJok see https://github.com/mkhairi/materialize-sass/issues/58
