### ISSUE TITLE
Bug: Caret for select inputs are deformed

### ISSUE THREAD

**Issue by rwu1997** [mkhairi/materialize-sass#80]
When trying to use select inputs, the caret(▼) displays incorrectly.

![image](https://cloud.githubusercontent.com/assets/10563314/12347107/b2028460-bb28-11e5-8162-02f31baf3ad1.png)

I was able to fix this by inspecting the `.caret` style:
```
.caret {
    display: inline-block;
    width: 0;
    height: 0;
    margin-left: 2px;
    vertical-align: middle;
    border-top: 4px dashed;
    border-top: 4px solid \9;
    border-right: 4px solid transparent;
    border-left: 4px solid transparent;
}
```
and by removing border-top and making width and height auto:
```
.caret {
	width: auto;
	height: auto;
	border-top: 0;
}
```

**Comment by mkhairi** [comment]
are you sure about this?.  it may related with other css class you defined. Everything looks fine to me. see http://materialize-rails.herokuapp.com/posts/new
