### ISSUE TITLE
Invalid CSS value

### ISSUE THREAD

**Issue by danReynolds** [mkhairi/materialize-sass#81]
I'm on Rails 4.2.3 and have sass version 3.4.2.1. The error I get is
```
Sass::SyntaxError - ("lighten-5": #E8F5E9, "lighten-4": #C8E6C9, "lighten-3": #A5D6A7, "lighten-2": #81C784, "lighten-1": #66BB6A, "base": #4CAF50, "darken-1": #43A047, "darken-
2": #388E3C, "darken-3": #2E7D32, "darken-4": #1B5E20, "accent-1": #B9F6CA, "accent-2": #69F0AE, "accent-3": #00E676, "accent-4": #00C853) isn't a valid CSS value.
```

Does anyone have experience with this issue? I have tried updating sass and sass-rails to no avail.

**Comment by danReynolds** [comment]
I just tried it on another project and it worked. I changed the gem version over to the one that worked at sass 3.4.14, sass-rails 5.0.3, tilt 1.4.1 but still not working.

**Comment by danReynolds** [comment]
Turns out I already had a $red color variable and it conflicted with a $red used in the colors file.

**Comment by gregcha** [comment]
I'm experiencing the same issue. removing my $red variable doesn't change anything. Did you do anything else? thank you
