### ISSUE TITLE
Click-to-toggle FAB

### ISSUE THREAD

**Issue by Pete-Tyldesley** [mkhairi/materialize-sass#83]
The current version of Materialize has a click-only fixed action button that is suitable for mobile (by adding click-to-toggle class). Unfortunately this isn't working with this gem and the actions still appear on hover. I have tried updating the gem to no avail.

**Comment by mkhairi** [comment]
hi  @Pete-Tyldesley,
check this out. http://materialize-rails.herokuapp.com.. its work. Double check you css class or javascript.
