### ISSUE TITLE
the mobile this not working

### ISSUE THREAD

**Issue by IgorVieira** [mkhairi/materialize-sass#85]
Please , I wanted to better understand why. Thank you for your attention
http://cryptic-dawn-79851.herokuapp.com

**Comment by mkhairi** [comment]
@IgorVieira try add this on you layout
```html
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
```

**Comment by IgorVieira** [comment]
Thanks It was a stupid mistake

**Comment by mvergarair** [comment]
Had the same issue. Thanks for the answer!
