### ISSUE TITLE
Scrollspy Uncaught Error

### ISSUE THREAD

**Issue by davidrichey** [mkhairi/materialize-sass#88]
I am working on a scrollspy nav with the example provider in the docs http://materializecss.com/scrollspy.html

My goal is to implement this with another jquery function show the navbar but I am getting an error
```Uncaught Error: Syntax error, unrecognized expression: a[href=#introduction]```

This prevents any further jquery from running.

Example View
```
<div class="row">
  <div class="col s12 m9 l10">
    <div id="introduction" class="section scrollspy">
      <p>Content </p>
    </div>

    <div id="structure" class="section scrollspy">
      <p>Content </p>
    </div>

    <div id="initialization" class="section scrollspy">
      <p>Content </p>
    </div>
  </div>
  <div class="col hide-on-small-only m3 l2">
    <ul class="section table-of-contents">
      <li><a href="#introduction">Introduction</a></li>
      <li><a href="#structure">Structure</a></li>
      <li><a href="#initialization">Intialization</a></li>
    </ul>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('.scrollspy').scrollSpy();

    console.log('Not Executing')
  });
</script>
```

**Comment by mkhairi** [comment]
https://github.com/Dogfalo/materialize/issues/2779

**Comment by davidrichey** [comment]
Thank you for the info. I saw you added in the updates for scrollspy. Are you planning on releasing a updated version of the gem?

**Comment by mkhairi** [comment]
@davidrichey Sure, for now, you can update gem direct from master branch. I will published gem version with same as official materialize release later.

**Comment by davidrichey** [comment]
It is causing an error using the master branch using aws beanstalk. Just curious no urgency @mkhairi

**Comment by davidrichey** [comment]
New version pushing soon? @mkhairi

**Comment by mkhairi** [comment]
@davidrichey  v0.97.6 published...
