### ISSUE TITLE
Scrollable Tabs?

### ISSUE THREAD

**Issue by jakesorce** [mkhairi/materialize-sass#89]
I can't figure out how to make scrollable tabs. The documentation says it's possible but gives no examples. Any guidance here would be much appreciated

**Comment by lebart** [comment]
Just resize the documentation page and you will see the result. 
There nothing but the class to add to get the effect.

**Comment by lebart** [comment]
I think the tabs do this "naturally", if you analyze the code on the documentation page you will that they just use multiple .s3 to achieve this. The only limit I can see is the length of the text inside the tabs selector.

**Comment by mkhairi** [comment]
:+1:

**Comment by jakesorce** [comment]
yeah I can see that now. They just aren't as mobile friendly as I'd like them to be specially when you have tabs with more than 1 word or a longer word.
