### ISSUE TITLE
How to Merge all JS folder and what are the orders

### ISSUE THREAD

**Issue by IamHenryValdez** [mkhairi/materialize-sass#90]
I wanted to modify some JS scripts, but the materialize.js script is compressed ( Like the materialize.min.js).

So i just saw that all modules are in different js script. But I'd like to know how to merge them and what are the merging order. 

Thank You

**Comment by lebart** [comment]
Can you be more specific about the changes that you want to achieve? 
Cannot it be done by overriding or initialization process?

**Comment by mkhairi** [comment]
see [materialize-sprockets.js](https://github.com/mkhairi/materialize-sass/blob/master/app/assets/javascripts/materialize-sprockets.js)
