### ISSUE TITLE
Package is corrupt

### ISSUE THREAD

**Issue by hipertrix** [mkhairi/materialize-sass#92]
Hello, 
$> gem install materialize-sass

ERROR:  Error installing materialize-sass:
	invalid gem: package is corrupt, exception while verifying: undefined method `size' for nil:NilClass (NoMethodError) in /home/username/.rvm/gems/**ruby-2.1.3**/cache/materialize-sass-0.97.5.gem

............

Ops, Sorry. 
I tried  to
$> gem install materialize-sass -v 0.96.1
And sucess! It is ok.

**Comment by mkhairi** [comment]
new materialize-sass-0.97.6 released..
