### ISSUE TITLE
Can u include material icon

### ISSUE THREAD

**Issue by DRAKUN** [mkhairi/materialize-sass#94]
Material Design Lite uses a font called 'Material Icons'. You can either load this font from google, or host it yourself.

**Comment by mkhairi** [comment]
@DRAKUN  see [material_icons](https://github.com/Angelmmiguel/material_icons)

**Comment by DRAKUN** [comment]
its cool really but i use scss file then i dont know how do implement

**Comment by mkhairi** [comment]
@DRAKUN  just follow the gem read me, you should get it.

1. add ```gem 'material_icon' ``` in gem file
2. ```bundle install``` and restart rails server
3. add ```@import 'material_icons';``` in your ```application.scss``` file
4. ready to use ``<i class="material-icons">face</i>
<i class="material-icons md-36">face</i>```

**Comment by DRAKUN** [comment]
cool im ok thanks bro
