### ISSUE TITLE
Link_to application.scss

### ISSUE THREAD

**Issue by mafelix** [mkhairi/materialize-sass#95]
Rails is automatically assigning .css appended to every link_to in application.html.erb.
So when I open the console for the site. It does not find application.scss.css.
How do you actually link_to the sass/scss application file?

**Comment by lebart** [comment]
It's more a Rails question you should ask on stackoverflow. 

To give you an idea here is how you call the application.scss.css

In the layout: application.html.erb
`<%= stylesheet_link_tag  "front_end/application", media: "all", "data-turbolinks-track" => true %>`

Here is the documentation:
[official documentation](http://guides.rubyonrails.org/layouts_and_rendering.html)
