### ISSUE TITLE
turbolinks prevent adding 'active' to the inputs

### ISSUE THREAD

**Issue by gudata** [mkhairi/materialize-sass#96]
It seems that the active class is not added when you load a page via turbolinks.

http://materializecss.com/forms.html
Prefilling Text Inputs
If you are having trouble with the labels overlapping prefilled content, Try adding class="active" to the label

it might be my fault because I am using the betas of rails 5

**Comment by abartier** [comment]
Here I explain how I set validation with rails. This may helps you. 
https://github.com/mkhairi/materialize-sass/issues/93

**Comment by gudata** [comment]
Nice solution. Thanks!

**Comment by abartier** [comment]
You're welcome
