### ISSUE TITLE
TypeError: $(...).parallax is not a function(anonymous function)

### ISSUE THREAD

**Issue by DevilsNightsix** [mkhairi/materialize-sass#97]
I've got this error, when trying to initialize parallax
```
index.js:5 Uncaught TypeError: $(...).parallax is not a function(anonymous function) 
@ index.js:5fire 
@ jquery.js:3232self.fireWith 
@ jquery.js:3362jQuery.extend.ready 
@ jquery.js:3582completed 
@ jquery.js:3617 VM16009:88 Ember Inspector Active
```

my ```aplication.js```
```javascript
//= require jquery
//= require materialize-sprockes
//= require materialize/extras/nouislider
//= require jquery_ujs
//= require_tree .
```

I see in the inspector that the files loaded, but looks like plugins are not initialized.

**Comment by abartier** [comment]
Hi, 

You've got a typo there:

`//= require materialize-sprockes`

Should be

`//= require materialize-sprockets`

**Comment by DevilsNightsix** [comment]
@abartier Thanks, but error was caused because i'm trying to use materialize-sass with ember-cli-rails.

Ember-cli-rails includes it's own jquery, that overrides jquery defined with rails assets-pipeline.

So my solution was to install materialize as bower component and include javascript files in ```ember-cli-build.js```.

**Comment by abartier** [comment]
Ok, good to know for the ember-cli. 

Is it good enough to close this issue?

**Comment by DevilsNightsix** [comment]
Yep.
