### ISSUE TITLE
Parallax Modal - best practices

### ISSUE THREAD

**Issue by rubendinho** [mkhairi/materialize-sass#98]
I am using a large image (2000 x 1333) with Parallax, but the parallax effect is only showing a small piece of it. 

Is there a way to control the scaling of the the Parallax image effect using CSS?

Thanks

**Comment by mkhairi** [comment]
try add some css on your background class

``` background-size: cover;```

btw, you should ask this question at materialize official [materialize](https://github.com/Dogfalo/materialize) repo. Large community in there. thanks.

**Comment by rubendinho** [comment]
That doesn't help but I will try the official repo which is where I should have posted this anyway. Thanks!
